# Generated by Django 3.0.8 on 2020-07-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=500)),
                ('blog_head1', models.CharField(max_length=500)),
                ('blog_cont1', models.CharField(max_length=5000)),
                ('blog_head2', models.CharField(max_length=500)),
                ('blog_cont2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('blog_img', models.ImageField(upload_to=None)),
            ],
        ),
    ]
