# Generated by Django 3.0.8 on 2020-07-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=500)),
                ('post_content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('blog_img', models.ImageField(upload_to=None)),
            ],
        ),
    ]
