# Generated by Django 3.0.8 on 2020-07-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_img',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
