# Generated by Django 3.0.8 on 2020-07-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('content', models.CharField(max_length=5000)),
                ('timestamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
